bot:
  token: token
  owner: username

plugins:
  'helga.plugins:HelpPlugin':
    null
  'helga.plugins.quotes:QuotePlugin':
    null
  'helga.plugins.misc:MiscPlugin':
    null
  'helga.plugins.evil:PictureGrabber':
    null
